#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="dive"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./$name"

  # prepare context
  cd $tmp_dir

  case $platform in
  darwin)
    case $arch in
    arm64 | amd64) ;;
    *)
      log::error "[$(timestamp)] $platform unsupport arch: $arch"
      return 1
      ;;
    esac
    ;;
  linux)
    case $arch in
    arm64 | amd64) ;;
    *)
      log::error "[$(timestamp)] $platform unsupport arch: $arch"
      return 1
      ;;
    esac
    ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  # reference: https://github.com/wagoodman/dive/releases
  # example:
  #   -
  #   https://github.com/wagoodman/dive/releases/download/v0.12.0/dive_0.12.0_darwin_amd64.tar.gz
  #   https://github.com/wagoodman/dive/releases/download/v0.12.0/dive_0.12.0_darwin_arm64.tar.gz
  #   https://github.com/wagoodman/dive/releases/download/v0.12.0/dive_0.12.0_linux_amd64.tar.gz
  #   https://github.com/wagoodman/dive/releases/download/v0.12.0/dive_0.12.0_linux_arm64.tar.gz
  # generate url
  local url="https://github.com/wagoodman/dive/releases/download/$PACKAGE_CORE_VERSION/${name}_${PACKAGE_CORE_VERSION#v}_${platform}_${arch}.tar.gz"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1

  # install
  sudo mv $bin_file $usr_bin_dir

  # clean
  rm -rf $tmp_dir
}

export -f install
