#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="dive"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./$name"

  # prepare context
  cd $tmp_dir

  if [ "$(os::is_macos)" != "true" ] && [ "$arch" = "arm64" ]; then
    log::error "[$(timestamp)] unsupport linux arm64"
    return 1
  fi

  # reference: https://github.com/wagoodman/dive/releases
  # example:
  #   -
  #   https://github.com/wagoodman/dive/releases/download/v0.10.0/dive_0.10.0_darwin_amd64.tar.gz
  # generate url
  local url="https://github.com/wagoodman/dive/releases/download/$PACKAGE_CORE_VERSION/${name}_${PACKAGE_CORE_VERSION#v}_${platform}_${arch}.tar.gz"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1

  # install
  sudo mv $bin_file $usr_bin_dir

  # clean
  rm -rf $tmp_dir
}

export -f install
